services:
  exchangemocker:
    image: ${DOCKER_REGISTRY-}exchangemocker
    build:
        context: .
        dockerfile: ExchangeMocker/Dockerfile
    ports:
        - "8080:8080"

  hermes:
    image: ${DOCKER_REGISTRY-}hermes
    build:
        context: .
        dockerfile: Hermes/Dockerfile
    ports:
        - "7000:8080" 

  mnemosyne:
    image: ${DOCKER_REGISTRY-}mnemosyne
    build:
      context: .
      dockerfile: Mnemosyne/Dockerfile
    ports:
      - "7777:8080"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: mnemosynedb
        PGPORT: 5434
    ports: 
    - "5434:5434"
    volumes:
    - pgdata:/var/lib/postgresql/data
    - ./init_db.pgsql:/docker-entrypoint-initdb.d/init_db.pgsql

volumes:
  pgdata: